## Bonus 3
Přidej Sektor (poslední sloupec) jako vysvětlující proměnnou s využitím One Hot Encoding. Podívej se, které sektory mají kladný koeficient a které sektory mají záporný koeficient.

In [1]:
# Načtu si soubor
import pandas as pd
data = pd.read_csv('df.csv')
data.head()

,Company,CR,DA,FL,OPM,RT,TAT,DE,Y,PT,Sector
0,2Q3DU,1.19,0.20,2.21,0.0770,6.66,0.40,0.43,1.95,5.93,Industrials
1,46JNq,0.29,0.64,10.14,0.2037,20.04,0.36,6.52,7.26,43.48,Communication Services
2,4ISOt,2.93,0.04,1.43,0.3055,6.55,0.72,0.06,7.78,18.38,Communication Services
3,5AWwu,1.03,0.25,3.55,0.0708,146.43,1.80,0.88,6.17,5.15,Consumer Defensive
4,5hbZR,1.20,0.47,0.00,0.1677,30.92,0.93,0.00,0.00,17.06,Consumer Cyclical

In [2]:
# Podívám se na hodnoty ve sloupci 'Sector'
data['Sector'].unique()

array(['Industrials', 'Communication Services', 'Consumer Defensive',
       'Consumer Cyclical', 'Healthcare', 'Basic Materials', 'Technology',
       'Energy', 'Conglomerates', 'Financial Services'], dtype=object)

In [3]:
# Pomocí funkce 'get_dummies' vytvořím novou tabulku, kde je sloupec pro každou z těchto hodnot (True/False)  
sector_gd = pd.get_dummies(data['Sector'])
sector_gd

,Basic Materials,Communication Services,Conglomerates,Consumer Cyclical,Consumer Defensive,Energy,Financial Services,Healthcare,Industrials,Technology
0,False,False,False,False,False,False,False,False,True,False
1,False,True,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,True,False,False
96,False,False,False,False,True,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,True
98,False,False,False,False,False,False,False,False,False,True
99,False,False,False,False,False,False,False,True,False,False

In [4]:
# Původní data a novou tabulku propojím do nové tabulky
data_new = pd.merge(data, sector_gd, left_index=True, right_index=True)
data_new

,Company,CR,DA,FL,OPM,RT,TAT,DE,Y,PT,...,Basic Materials,Communication Services,Conglomerates,Consumer Cyclical,Consumer Defensive,Energy,Financial Services,Healthcare,Industrials,Technology
0,2Q3DU,1.19,0.20,2.21,0.0770,6.66,0.40,0.43,1.95,5.93,...,False,False,False,False,False,False,False,False,True,False
1,46JNq,0.29,0.64,10.14,0.2037,20.04,0.36,6.52,7.26,43.48,...,False,True,False,False,False,False,False,False,False,False
2,4ISOt,2.93,0.04,1.43,0.3055,6.55,0.72,0.06,7.78,18.38,...,False,True,False,False,False,False,False,False,False,False
3,5AWwu,1.03,0.25,3.55,0.0708,146.43,1.80,0.88,6.17,5.15,...,False,False,False,False,True,False,False,False,False,False
4,5hbZR,1.20,0.47,0.00,0.1677,30.92,0.93,0.00,0.00,17.06,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,yhCH3,1.50,0.37,2.33,0.2557,4.92,0.41,0.85,5.18,6.83,...,False,False,False,False,False,False,False,True,False,False
96,YqdX2,0.70,0.27,2.57,0.2363,16.11,0.64,0.69,7.40,2.70,...,False,False,False,False,True,False,False,False,False,False
97,yUjyz,1.49,0.12,2.36,0.2576,8.64,0.51,0.28,5.99,7.59,...,False,False,False,False,False,False,False,False,False,True
98,YX515,2.30,0.64,25.03,0.3758,7.48,0.31,16.08,41.57,10.54,...,False,False,False,False,False,False,False,False,False,True
99,zCRGR,1.40,0.21,2.35,0.2391,7.08,0.45,0.50,3.35,5.53,...,False,False,False,False,False,False,False,True,False,False

In [14]:
# Některé sloupce (s víceslovným názvem) přejmenuji, abych je mohla uvést v rovnici pro regresní model
data_new.rename(columns={'Financial Services': 'FinancialServices', 'Consumer Defensive': 'ConsumerDefensive',
                         'Consumer Cyclical': 'ConsumerCyclical', 'Communication Services': 'CommunicationServices',
                         'Basic Materials': 'BasicMaterials'}, inplace=True)
data_new.head()

,Company,CR,DA,FL,OPM,RT,TAT,DE,Y,PT,...,BasicMaterials,CommunicationServices,Conglomerates,ConsumerCyclical,ConsumerDefensive,Energy,FinancialServices,Healthcare,Industrials,Technology
0,2Q3DU,1.19,0.20,2.21,0.0770,6.66,0.40,0.43,1.95,5.93,...,False,False,False,False,False,False,False,False,True,False
1,46JNq,0.29,0.64,10.14,0.2037,20.04,0.36,6.52,7.26,43.48,...,False,True,False,False,False,False,False,False,False,False
2,4ISOt,2.93,0.04,1.43,0.3055,6.55,0.72,0.06,7.78,18.38,...,False,True,False,False,False,False,False,False,False,False
3,5AWwu,1.03,0.25,3.55,0.0708,146.43,1.80,0.88,6.17,5.15,...,False,False,False,False,True,False,False,False,False,False
4,5hbZR,1.20,0.47,0.00,0.1677,30.92,0.93,0.00,0.00,17.06,...,False,False,False,True,False,False,False,False,False,False

In [15]:
# Nechám vytvořit regresní model a zobrazit k němu souhrnnou tabulku
import statsmodels.formula.api as smf

formula = 'Y ~ BasicMaterials + CommunicationServices + Conglomerates + ConsumerCyclical + ConsumerDefensive + Energy + FinancialServices + Healthcare + Industrials + Technology'
mod = smf.ols(formula=formula, data=data_new)
res = mod.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.154
Model:                            OLS   Adj. R-squared:                  0.069
Method:                 Least Squares   F-statistic:                     1.815
Date:                Mon, 06 Nov 2023   Prob (F-statistic):             0.0761
Time:                        22:58:35   Log-Likelihood:                -422.18
No. Observations:                 100   AIC:                             864.4
Df Residuals:                      90   BIC:                             890.4
Df Model:                           9
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                        10.6340      2.387      4.454      0.000       5.891      15.377
BasicMaterials[T.True]            0.5326      9.387      0.057      0.955     -18.117      19.182
CommunicationServices[T.True]    -5.9830      5.516     -1.085      0.281     -16.942       4.975
Conglomerates[T.True]            -4.4240     15.905     -0.278      0.782     -36.022      27.174
ConsumerCyclical[T.True]         14.3883      4.972      2.894      0.005       4.511      24.266
ConsumerDefensive[T.True]         6.1910      5.516      1.122      0.265      -4.768      17.149
Energy[T.True]                   -8.3024      6.849     -1.212      0.229     -21.909       5.305
FinancialServices[T.True]        11.8660      9.387      1.264      0.209      -6.784      30.516
Healthcare[T.True]               -3.1885      4.250     -0.750      0.455     -11.632       5.255
Industrials[T.True]              -4.4748      4.833     -0.926      0.357     -14.077       5.128
Technology[T.True]                4.0290      4.250      0.948      0.346      -4.414      12.472
==============================================================================
Omnibus:                       94.099   Durbin-Watson:                   1.775
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              892.118
Skew:                           3.128   Prob(JB):                    1.90e-194
Kurtosis:                      16.228   Cond. No.                     2.15e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.47e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
# Kladný koeficient mají sektory: Basic Materials, Consumer Cyclical, Consumer Defensive, Financial Services, Technology
# Záporný koeficient mají sektory: Communication Services, Conglomerates, Energy, Healthcare, Industrials